#!/usr/bin/php
<?php

// Obfuscate:
//  We dont like clear text pwds in html area nor in backups
//  may not be the safest way but better than nothing
echo "// Append/pipe the following to your credentials file:" . PHP_EOL;
echo "\$this->ad_pass = '" . trim(base64_encode(str_rot13($argv[1]))) . "';" . PHP_EOL;

?>
